name: patapsco
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - beautifulsoup4
  - ftfy
  - jieba
  - more-itertools
  - nltk
  - numpy
  - psutil
  - pydantic>=1.7.1,<1.8.0
  - pyjnius
  - pymorphy2
  - pyyaml
  - sacremoses
  - spacy>=3.0.0
  - spacy-pkuseg>=0.0.27,<0.1.0
  - sqlitedict
  - stanza>=1.2.0
  - pip
  - pip:
    - pyserini
    - pytrec_eval
