name: patapsco
channels:
  - condaforge
  - stanfordnlp
dependencies:
  - python>=3.6
  - beautifulsoup4
  - more-itertools
  - numpy
  - pyyaml
  - spacy>=3.0.0
  - spacy-pkuseg>=0.0.27,<0.1.0
  - stanza>=1.2.0
  - pip
  - pip:
    - jieba
    - pydantic>=1.7.1,<1.8.0
    - pyserini
    - pytrec_eval
    - scriptnorm
    - sqlitedict
