run:
  name: English basic run

documents:
  input:
    format: json
    lang: en
    encoding: utf8
    path: samples/data/en_mini_dataset.jsonl
  process:
    normalize:
      report: true
    tokenize:
      name: whitespace
    lowercase: true
    stem:
      name: mock
  comment: Mini English dataset

index:
  name: lucene

topics:
  input:
    format: json
    lang: en
    encoding: utf8
    path: samples/data/en_mini_topics.jsonl
  fields: title

queries:
  process:
    inherit: documents.process

retrieve:
  name: bm25
  number: 5

rerank:
  name: mock

score:
  input:
    format: trec
    path: samples/data/en_mini_dataset_qrels
  metrics:
    - map
    - P@20
    - ndcg
