run:
  name: English basic run

documents:
  input:
    format: json
    lang: eng
    encoding: utf8
    path: samples/data/eng_mini_docs.jsonl
  process:
    normalize:
      lowercase: true
    tokenize: whitespace
    stem: porter
  comment: Mini English dataset
  output: true

database:
  name: sqlite

index:
  name: lucene

topics:
  input:
    format: json
    lang: eng
    encoding: utf8
    path: samples/data/eng_mini_topics.jsonl
  fields: title

queries:
  process:
    normalize:
      lowercase: true
    tokenize: spacy
    stem: spacy
    strict_check: off

retrieve:
  name: bm25
  number: 5

rerank:
  name: mock

score:
  input:
    path: samples/data/eng_mini_qrels
