run:
  name: English qsub
  parallel:
    name: qsub
  stage1:
    num_jobs: 2

documents:
  input:
    format: json
    lang: eng
    encoding: utf8
    path: samples/data/eng_mini_docs.jsonl
  process:
    tokenize: whitespace

database:
  name: sqlite

index:
  name: lucene

topics:
  input:
    format: json
    lang: eng
    encoding: utf8
    path: samples/data/eng_mini_topics.jsonl
  fields: title

queries:
  process:
    inherit: documents.process

retrieve:
  name: bm25
  number: 5

score:
  input:
    path: samples/data/eng_mini_qrels
