run:
  name: English basic run

text:
  normalize:
    lowercase: true
  tokenize: whitespace
  stem: porter

documents:
  input:
    format: json
    lang: eng
    encoding: utf8
    path: samples/data/eng_mini_docs.jsonl
  process:
    inherit: text
  comment: Mini English dataset
  output: true

database:
  name: sqlite

index:
  name: lucene

topics:
  input:
    format: json
    lang: eng
    encoding: utf8
    path: samples/data/eng_mini_topics.jsonl
  fields: title

queries:
  process:
    inherit: text

retrieve:
  name: bm25
  number: 5

rerank:
  name: mock

score:
  input:
    path: samples/data/eng_mini_qrels
