run:
  name: ir_datasets testing using vaswani(11k docs)

text:
  normalize:
    lowercase: true
  tokenize: whitespace
  stem: porter

documents:
  input:
    format: irds
    lang: eng
    path: vaswani
  process:
    inherit: text
  output: true

database:
  name: sqlite

index:
  name: lucene

topics:
  input:
    format: irds
    lang: eng
    source: original
    encoding: utf8
    path: vaswani

queries:
  process:
    inherit: text

retrieve:
  name: bm25
  number: 200

score:
  input:
    format: irds
    path: vaswani
