run:
  name: Chinese sample run
  comment: The translations in the topic file are from Google translate.

documents:
  input:
    format: json
    lang: zho
    encoding: utf8
    path: samples/data/zho_mini_docs.jsonl
  process:
    tokenize: spacy

database:
  name: sqlite

index:
  name: lucene

topics:
  input:
    format: json
    lang: zho
    source: google translate
    encoding: utf8
    path: samples/data/eng_mini_topics.jsonl
  fields: title

queries:
  process:
    inherit: documents.process

retrieve:
  name: bm25
  number: 5

score:
  input:
    path: samples/data/eng_mini_qrels
